{% set name = "OpenMiChroM" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - openmm
    - h5py
    - numpy
    - pandas
    - pip
    - python >=3.10
    - scikit-learn
    - scipy
  run:
    - openmm
    - h5py
    - numpy
    - pandas
    - python >=3.10
    - scikit-learn
    - scipy

test:
  imports:
    - OpenMiChroM

about:
  home: https://ndb.rice.edu/Open-MiChroM
  summary: Open-Michrom lib for chromosome simulations
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://open-michrom.readthedocs.io
  dev_url: https://github.com/junioreif/OpenMiChroM

extra:
  recipe-maintainers:
    - junioreif
