{% set name = "OpenMiChroM" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/e5/7c/16223eb7d05efa20f8cb1061f287fc35ed2c397a15cc959d02f10b8e6a03/openmichrom-1.1.0.tar.gz"
  sha256: a2cd3ae826b0af507dc68b0870d25cbf7835e2954e9c96c14f0de33d43aadf00

build:
  number: 0
  noarch: pyhton
  entry_points:
    - CLINAME=OpenMiChroM._cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - openmm
    - h5py
    - numpy
    - pandas
    - pip
    - python
    - scikit-learn
    - scipy
  run:
    - openmm
    - h5py
    - numpy
    - pandas
    - python
    - scikit-learn
    - scipy

test:
  imports:
    - OpenMiChroM

about:
  home: https://ndb.rice.edu/Open-MiChroM
  summary: Open-Michrom lib for chromosome simulations
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://open-michrom.readthedocs.io
  dev_url: https://github.com/junioreif/OpenMiChroM

extra:
  recipe-maintainers:
    - junioreif