import json
import os
import subprocess
import sys
import functools
import threading
from contextlib import contextmanager
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

import h5py
import numpy as np
import pytest

from OpenMiChroM.CndbTools import CndbTools
from OpenMiChroM._structural_io import detect_structural_file


class _NoRangeRequestHandler(SimpleHTTPRequestHandler):
    def log_message(self, format, *args):
        return


@contextmanager
def _serve_no_range_directory(directory):
    factory = functools.partial(_NoRangeRequestHandler, directory=str(directory))
    server = ThreadingHTTPServer(("127.0.0.1", 0), factory)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        host, port = server.server_address
        yield f"http://{host}:{port}"
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


def test_detect_simple_local_cndb(tmp_path):
    path = tmp_path / "simple.cndb"
    with h5py.File(path, "w") as handle:
        handle.create_dataset("types", data=np.array([b"A1", b"B1", b"A1"]))
        handle.create_dataset("1", data=np.arange(9, dtype=np.float32).reshape(3, 3))
        handle.create_dataset("2", data=np.arange(9, dtype=np.float32).reshape(3, 3))

    info = detect_structural_file(path)

    assert info.file_type == "cndb"
    assert info.layout == "openmichrom-simple-cndb"
    assert info.frame_count == 2
    assert info.bead_count == 3
    assert info.dtype == "float32"
    assert info.direct_streaming_supported is True


def test_detect_nested_hdf5_spacewalk_layout(tmp_path):
    path = tmp_path / "nested.sw"
    with h5py.File(path, "w") as handle:
        handle.create_group("Header")
        group = handle.create_group("replica1_chr1")
        spatial = group.create_group("spatial_position")
        spatial.create_dataset("1", data=np.arange(12, dtype=np.float32).reshape(4, 3))
        group.create_dataset("genomic_position", data=np.array([[1, 50000], [50001, 100000]]))

    info = detect_structural_file(path)

    assert info.file_type == "sw"
    assert info.layout == "nested-ndb-swb"
    assert info.trajectories == ["replica1_chr1"]
    assert info.frame_count == 1
    assert info.bead_count == 4
    assert info.coordinate_paths == ["/replica1_chr1/spatial_position/1"]


def test_cndbtools_open_reads_local_nested_spacewalk_layout(tmp_path):
    path = tmp_path / "nested.sw"
    coords = np.arange(12, dtype=np.float32).reshape(4, 3)
    with h5py.File(path, "w") as handle:
        handle.create_group("Header")
        group = handle.create_group("replica1_chr1")
        group.create_dataset("types", data=np.array([b"A1", b"B1", b"A1", b"B1"]))
        spatial = group.create_group("spatial_position")
        spatial.create_dataset("t_0", data=coords)

    tools = CndbTools.open(str(path), trajectory="replica1_chr1")
    xyz = tools.xyz(frames=[0], beadSelection=range(1, 3))

    assert tools.is_remote is False
    assert tools.frame_ids == ["t_0"]
    assert tools.dictChromSeq["A1"] == [0, 2]
    assert xyz.shape == (1, 2, 3)
    np.testing.assert_array_equal(xyz[0], coords[1:3])


def test_detect_text_ndb(tmp_path):
    path = tmp_path / "toy.ndb"
    path.write_text(
        "HEADER    NDB File generated by OpenMiChroM\n"
        "MODEL        1\n"
        "CHROM         1 A1          C1        1   0.000   1.000   2.000         1      50000    0.000\n"
        "ENDMDL\n"
        "END\n",
        encoding="utf-8",
    )

    info = detect_structural_file(path)

    assert info.file_type == "ndb"
    assert info.layout == "text-ndb"
    assert info.detected_text_ndb is True


def test_cndbtools_open_reads_local_text_ndb(tmp_path):
    path = tmp_path / "toy.ndb"
    path.write_text(
        "HEADER    NDB File generated by OpenMiChroM\n"
        "MODEL 1\n"
        "CHROM 1 A1 C1 1 0.0 1.0 2.0 1 50000 0.0\n"
        "CHROM 2 B1 C1 2 3.0 4.0 5.0 50001 100000 0.0\n"
        "ENDMDL\n"
        "MODEL 2\n"
        "CHROM 1 A1 C1 1 10.0 11.0 12.0 1 50000 0.0\n"
        "CHROM 2 B1 C1 2 13.0 14.0 15.0 50001 100000 0.0\n"
        "ENDMDL\n"
        "END\n",
        encoding="utf-8",
    )

    tools = CndbTools.open(str(path))
    xyz = tools.xyz(frames=[1, 2], beadSelection=[1])

    assert tools.Nframes == 2
    assert tools.Nbeads == 2
    assert tools.dictChromSeq == {"A1": [0], "B1": [1]}
    assert xyz.shape == (2, 1, 3)
    np.testing.assert_array_equal(
        xyz[:, 0, :],
        np.array([[3.0, 4.0, 5.0], [13.0, 14.0, 15.0]], dtype=np.float32),
    )


def test_cndbtools_open_preserves_local_cndb_behavior(tmp_path):
    path = tmp_path / "simple.cndb"
    coords = np.arange(12, dtype=np.float32).reshape(4, 3)
    with h5py.File(path, "w") as handle:
        handle.create_dataset("types", data=np.array([b"A1", b"B1", b"A1", b"B1"]))
        handle.create_dataset("1", data=coords)

    tools = CndbTools.open(str(path))
    xyz = tools.xyz(frames=[1], beadSelection=range(0, 2))

    assert tools.is_remote is False
    assert xyz.shape == (1, 2, 3)
    np.testing.assert_array_equal(xyz[0], coords[:2])


def test_remote_nonindexed_hdf5_requires_explicit_download_fallback(tmp_path):
    path = tmp_path / "simple.cndb"
    coords = np.arange(12, dtype=np.float32).reshape(4, 3)
    with h5py.File(path, "w") as handle:
        handle.create_dataset("types", data=np.array([b"A1", b"B1", b"A1", b"B1"]))
        handle.create_dataset("1", data=coords)

    with _serve_no_range_directory(tmp_path) as base_url:
        url = f"{base_url}/{path.name}"
        info = detect_structural_file(url)
        assert info.detected_hdf5 is True
        assert info.range_supported is False

        with pytest.raises(ValueError, match="cannot be streamed safely"):
            CndbTools.open(url)

        with pytest.raises(ValueError, match="exceeds"):
            CndbTools.open(url, allow_download=True, max_download_size_mb=0.0001)

        tools = CndbTools.open(
            url,
            allow_download=True,
            max_download_size_mb=1,
            download_cache_path=tmp_path / "downloaded.cndb",
        )

    assert tools.is_remote is False
    assert Path(tools.downloaded_remote_path).name == "downloaded.cndb"
    np.testing.assert_array_equal(
        tools.xyz(frames=[1], beadSelection=range(1, 3))[0],
        coords[1:3],
    )


def test_inspect_structural_file_cli_json(tmp_path):
    path = tmp_path / "simple.cndb"
    with h5py.File(path, "w") as handle:
        handle.create_dataset("types", data=np.array([b"A1"]))
        handle.create_dataset("1", data=np.zeros((1, 3), dtype=np.float32))

    result = subprocess.run(
        [
            sys.executable,
            "scripts/inspect_structural_file.py",
            "--path",
            str(path),
            "--json",
        ],
        cwd=os.environ.get("OPENMICHROM_REPO", os.getcwd()),
        text=True,
        capture_output=True,
        check=True,
    )
    payload = json.loads(result.stdout)

    assert payload["file_type"] == "cndb"
    assert payload["layout"] == "openmichrom-simple-cndb"


def test_cndbtools_import_does_not_require_openmm():
    repo_root = os.getcwd()
    code = """
import builtins
real_import = builtins.__import__
def guarded_import(name, *args, **kwargs):
    if name == 'openmm' or name.startswith('openmm.'):
        raise ImportError('blocked openmm import')
    return real_import(name, *args, **kwargs)
builtins.__import__ = guarded_import
from OpenMiChroM.CndbTools import CndbTools
print(CndbTools.__name__)
"""
    env = os.environ.copy()
    env["PYTHONPATH"] = repo_root + os.pathsep + env.get("PYTHONPATH", "")
    result = subprocess.run(
        [sys.executable, "-c", code],
        cwd=repo_root,
        env=env,
        text=True,
        capture_output=True,
        check=True,
    )
    assert "cndbTools" in result.stdout
