import h5py
import numpy as np
import pytest
import subprocess
import sys

from OpenMiChroM.CndbTools import CndbTools, convert_structure_file
from OpenMiChroM._structural_io.readers import NDBTextReader


def _write_tiny_ndb(path):
    path.write_text(
        "HEADER    NDB File generated by OpenMiChroM\n"
        "TITLE     tiny\n"
        "SEQCHR   1 C1     3  A1 B1 A2\n"
        "MODEL 1\n"
        "CHROM         1 A1 C1         1      0.000      1.000      2.000          1      50000    0.000\n"
        "CHROM         2 B1 C1         2      3.000      4.000      5.000      50001     100000    0.000\n"
        "CHROM         3 A2 C1         3      6.000      7.000      8.000     100001     150000    0.000\n"
        "ENDMDL\n"
        "MODEL 2\n"
        "CHROM         1 A1 C1         1     10.000     11.000     12.000          1      50000    0.000\n"
        "CHROM         2 B1 C1         2     13.000     14.000     15.000      50001     100000    0.000\n"
        "CHROM         3 A2 C1         3     16.000     17.000     18.000     100001     150000    0.000\n"
        "ENDMDL\n"
        "END\n",
        encoding="utf-8",
    )


def _write_tiny_spacewalk(path):
    path.write_text(
        "##format=sw1 name=tiny_spacewalk genome=hg38\n"
        "chromosome\tstart\tend\tx\ty\tz\n"
        "trace 0\n"
        "chr21\t1\t50000\t0.000\t1.000\t2.000\n"
        "chr21\t50001\t100000\t3.000\t4.000\t5.000\n"
        "trace 1\n"
        "chr21\t1\t50000\t10.000\t11.000\t12.000\n"
        "chr21\t50001\t100000\t13.000\t14.000\t15.000\n",
        encoding="utf-8",
    )


def _write_tiny_gro(path):
    path.write_text(
        "tiny frame 1\n"
        "3\n"
        "    1ASP     CA    1   0.000   1.000   2.000\n"
        "    2HIS     CA    2   3.000   4.000   5.000\n"
        "    3GLU     CA    3   6.000   7.000   8.000\n"
        "10.0 10.0 10.0\n"
        "tiny frame 2\n"
        "3\n"
        "    1ASP     CA    1  10.000  11.000  12.000  0.1000  0.2000  0.3000\n"
        "    2HIS     CA    2  13.000  14.000  15.000  0.1000  0.2000  0.3000\n"
        "    3GLU     CA    3  16.000  17.000  18.000  0.1000  0.2000  0.3000\n"
        "10.0 10.0 10.0\n",
        encoding="utf-8",
    )


def test_tiny_ndb_to_cndb_to_ndb_roundtrip(tmp_path):
    ndb_path = tmp_path / "tiny.ndb"
    cndb_path = tmp_path / "tiny.cndb"
    roundtrip_path = tmp_path / "tiny_roundtrip.ndb"
    _write_tiny_ndb(ndb_path)

    result = convert_structure_file(ndb_path, cndb_path)

    assert result == cndb_path
    with h5py.File(cndb_path, "r") as h5:
        assert "Header" in h5
        assert "_index" in h5
        assert "_index_offset" in h5.attrs
        assert h5["Header"].attrs["format_name"] == "OpenMiChroM-CNDB"
        np.testing.assert_array_equal(
            h5["1"][()],
            np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]], dtype=np.float32),
        )

    convert_structure_file(cndb_path, roundtrip_path)
    reader = NDBTextReader(roundtrip_path)
    assert reader.frame_ids == ["1", "2"]
    assert reader.types == ["A1", "B1", "A2"]
    np.testing.assert_array_equal(
        reader.get_coordinates(2),
        np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]], dtype=np.float32),
    )


def test_tiny_cndb_to_ndb(tmp_path):
    cndb_path = tmp_path / "tiny.cndb"
    ndb_path = tmp_path / "tiny.ndb"
    with h5py.File(cndb_path, "w") as h5:
        h5.create_dataset("types", data=np.array([b"A1", b"B1"]))
        h5.create_dataset("1", data=np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32))

    convert_structure_file(cndb_path, ndb_path)

    reader = NDBTextReader(ndb_path)
    assert reader.types == ["A1", "B1"]
    np.testing.assert_array_equal(
        reader.get_coordinates(1),
        np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32),
    )


def test_tiny_ndb_to_pdb_and_simple_pdb_to_ndb(tmp_path):
    ndb_path = tmp_path / "tiny.ndb"
    pdb_path = tmp_path / "tiny.pdb"
    from_pdb_path = tmp_path / "from_pdb.ndb"
    _write_tiny_ndb(ndb_path)

    convert_structure_file(ndb_path, pdb_path)

    text = pdb_path.read_text(encoding="utf-8")
    assert "MODEL" in text
    assert "ATOM" in text
    assert "ASP" in text

    CndbTools.convert(pdb_path, from_pdb_path)
    reader = NDBTextReader(from_pdb_path)
    assert reader.types[:3] == ["A1", "B1", "A2"]
    assert reader.get_coordinates(1).shape == (3, 3)


def test_tiny_ndb_to_pdb_with_custom_fields(tmp_path):
    ndb_path = tmp_path / "tiny.ndb"
    pdb_path = tmp_path / "tiny.pdb"
    _write_tiny_ndb(ndb_path)

    convert_structure_file(
        ndb_path,
        pdb_path,
        pdb_atom_name="BB",
        pdb_residue_name="CHR",
        pdb_chain_id="B",
        pdb_element="C",
    )

    atom_lines = [line for line in pdb_path.read_text(encoding="utf-8").splitlines() if line.startswith("ATOM")]
    assert atom_lines
    assert " BB " in atom_lines[0]
    assert "CHR B" in atom_lines[0]
    assert atom_lines[0].rstrip().endswith("C")


def test_tiny_gro_to_cndb(tmp_path):
    gro_path = tmp_path / "tiny.gro"
    cndb_path = tmp_path / "tiny.cndb"
    _write_tiny_gro(gro_path)

    convert_structure_file(gro_path, cndb_path)

    with h5py.File(cndb_path, "r") as h5:
        assert sorted(name for name in h5 if name.isdigit()) == ["1", "2"]
        assert [value.decode("utf-8") for value in h5["types"][()]] == ["A1", "B1", "A2"]
        np.testing.assert_array_equal(
            h5["2"][()],
            np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]], dtype=np.float32),
        )


def test_convert_frame_and_bead_subset(tmp_path):
    ndb_path = tmp_path / "tiny.ndb"
    cndb_path = tmp_path / "subset.cndb"
    _write_tiny_ndb(ndb_path)

    convert_structure_file(ndb_path, cndb_path, frames=[2], start=1, stop=3)

    with h5py.File(cndb_path, "r") as h5:
        assert sorted(name for name in h5 if name.isdigit()) == ["2"]
        np.testing.assert_array_equal(
            h5["2"][()],
            np.array([[13, 14, 15], [16, 17, 18]], dtype=np.float32),
        )
        assert [value.decode("utf-8") for value in h5["types"][()]] == ["B1", "A2"]


def test_convert_memory_guard_can_be_overridden(tmp_path):
    ndb_path = tmp_path / "tiny.ndb"
    cndb_path = tmp_path / "tiny.cndb"
    _write_tiny_ndb(ndb_path)

    with pytest.raises(ValueError, match="Estimated converted coordinate payload"):
        convert_structure_file(ndb_path, cndb_path, max_memory_mb=0)

    convert_structure_file(ndb_path, cndb_path, max_memory_mb=0, allow_large=True)
    assert cndb_path.exists()


def test_supported_hdf5_sw_to_ndb(tmp_path):
    sw_path = tmp_path / "toy.sw"
    ndb_path = tmp_path / "toy.ndb"
    coords = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
    with h5py.File(sw_path, "w") as h5:
        h5.create_group("Header")
        group = h5.create_group("replica1_chr1")
        group.create_dataset("types", data=np.array([b"A1", b"B1"]))
        group.create_dataset("genomic_position", data=np.array([[1, 50000], [50001, 100000]]))
        spatial = group.create_group("spatial_position")
        spatial.create_dataset("t_1", data=coords)

    convert_structure_file(sw_path, ndb_path, trajectory="replica1_chr1")

    reader = NDBTextReader(ndb_path)
    assert reader.types == ["A1", "B1"]
    np.testing.assert_array_equal(reader.get_coordinates(1), coords)


def test_text_spacewalk_to_ndb(tmp_path):
    sw_path = tmp_path / "toy.spw"
    ndb_path = tmp_path / "toy.ndb"
    _write_tiny_spacewalk(sw_path)

    convert_structure_file(sw_path, ndb_path)

    reader = NDBTextReader(ndb_path)
    assert reader.frame_ids == ["1", "2"]
    assert reader.types == ["UN", "UN"]
    np.testing.assert_array_equal(
        reader.get_coordinates(2),
        np.array([[10, 11, 12], [13, 14, 15]], dtype=np.float32),
    )


def test_text_spacewalk_to_cndb(tmp_path):
    sw_path = tmp_path / "toy.sw"
    cndb_path = tmp_path / "toy.cndb"
    _write_tiny_spacewalk(sw_path)

    convert_structure_file(sw_path, cndb_path)

    with h5py.File(cndb_path, "r") as h5:
        assert "Header" in h5
        assert "_index" in h5
        np.testing.assert_array_equal(
            h5["1"][()],
            np.array([[0, 1, 2], [3, 4, 5]], dtype=np.float32),
        )
        assert [value.decode("utf-8") for value in h5["types"][()]] == ["UN", "UN"]


def test_ndb_to_text_spacewalk_roundtrip(tmp_path):
    ndb_path = tmp_path / "tiny.ndb"
    sw_path = tmp_path / "tiny.spw"
    roundtrip_path = tmp_path / "roundtrip.ndb"
    _write_tiny_ndb(ndb_path)

    convert_structure_file(ndb_path, sw_path)

    text = sw_path.read_text(encoding="utf-8")
    assert text.startswith("##format=sw1")
    assert "trace 0" in text
    assert "chr1" in text

    convert_structure_file(sw_path, roundtrip_path)
    reader = NDBTextReader(roundtrip_path)
    np.testing.assert_array_equal(
        reader.get_coordinates(1),
        np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]], dtype=np.float32),
    )


def test_converter_rejects_remote_urls():
    with pytest.raises(ValueError, match="local-file only"):
        convert_structure_file(
            "https://example.org/file.cndb",
            output_format="ndb",
        )


def test_convert_structure_file_cli(tmp_path):
    ndb_path = tmp_path / "tiny.ndb"
    cndb_path = tmp_path / "tiny.cndb"
    _write_tiny_ndb(ndb_path)

    result = subprocess.run(
        [
            sys.executable,
            "scripts/convert_structure_file.py",
            str(ndb_path),
            str(cndb_path),
        ],
        text=True,
        capture_output=True,
        check=True,
    )

    assert str(cndb_path) in result.stdout
    with h5py.File(cndb_path, "r") as h5:
        assert "Header" in h5
        assert "_index" in h5


def test_convert_structure_file_cli_accepts_frame_and_bead_filters(tmp_path):
    ndb_path = tmp_path / "tiny.ndb"
    cndb_path = tmp_path / "tiny.cndb"
    _write_tiny_ndb(ndb_path)

    subprocess.run(
        [
            sys.executable,
            "scripts/convert_structure_file.py",
            str(ndb_path),
            str(cndb_path),
            "--frames",
            "1",
            "--start",
            "0",
            "--stop",
            "2",
        ],
        text=True,
        capture_output=True,
        check=True,
    )

    with h5py.File(cndb_path, "r") as h5:
        assert h5["1"].shape == (2, 3)


def test_convert_structure_file_cli_refuses_unimplemented_dtype_filter(tmp_path):
    ndb_path = tmp_path / "tiny.ndb"
    cndb_path = tmp_path / "tiny.cndb"
    _write_tiny_ndb(ndb_path)

    result = subprocess.run(
        [
            sys.executable,
            "scripts/convert_structure_file.py",
            str(ndb_path),
            str(cndb_path),
            "--coordinate-dtype",
            "float64",
        ],
        text=True,
        capture_output=True,
    )

    assert result.returncode != 0
    assert "Dtype-filtered conversion is not implemented yet" in result.stderr
